'use client';

import React from 'react';
import { PublicNavbar } from '@/components/public/PublicNavbar';
import { PublicFooter } from '@/components/public/PublicFooter';
import { FadeIn } from '@/components/motion/MotionPrimitives';
import { AlertTriangle, ShieldCheck } from 'lucide-react';

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-white dark:bg-zinc-950 text-zinc-900 dark:text-zinc-100 flex flex-col">
      <PublicNavbar />

      <main className="flex-1 pt-24 pb-16">
        <section className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 pt-12 pb-16">
          <FadeIn>
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-amber-500/30 bg-amber-500/10 text-xs font-medium text-amber-700 dark:text-amber-400 mb-6">
              <AlertTriangle className="w-3.5 h-3.5" />
              <span>IRDAI Regulatory Notice</span>
            </div>
            <h1 className="text-3xl sm:text-4xl font-extrabold tracking-tight text-zinc-900 dark:text-zinc-50">
              Regulatory & Decision-Support Disclaimer
            </h1>
            <p className="mt-3 text-xs text-zinc-500 font-mono">
              Statutory disclosure regarding insurance advisory boundaries
            </p>
          </FadeIn>

          <div className="mt-10 space-y-8 text-xs text-zinc-600 dark:text-zinc-400 leading-relaxed">
            <div className="p-4 rounded-xl border border-amber-200 dark:border-amber-900/40 bg-amber-50/50 dark:bg-amber-950/20 text-amber-900 dark:text-amber-300">
              <div className="font-bold mb-1">Important Notice:</div>
              <p>
                VeriSure is a technology decision-support tool. It is NOT an insurance company, licensed insurance broker, corporate agent, or underwriting authority under the Insurance Regulatory and Development Authority of India (IRDAI).
              </p>
            </div>

            <section className="space-y-2">
              <h2 className="text-base font-bold text-zinc-900 dark:text-zinc-100">
                1. Deterministic Projections vs. Final Settlement
              </h2>
              <p>
                The financial comparisons generated by the "Claim vs. Self-Pay" decision engine are deterministic projections calculated from user-provided policy schedules, standard IRDAI motor tariff depreciation schedules, and workshop repair estimates. Actual claim settlement amounts may vary based on insurer-specific policy wording, endorsement endorsements, or on-site loss assessor findings.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-base font-bold text-zinc-900 dark:text-zinc-100">
                2. No-Claim Bonus (NCB) Resets
              </h2>
              <p>
                Projections regarding multi-year NCB loss assume standard IRDAI NCB step-down rules (e.g., loss of entire NCB upon claim registration unless an explicit NCB Protect add-on is active). Policyholders should review their individual policy certificates for insurer-specific terms.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-base font-bold text-zinc-900 dark:text-zinc-100">
                3. Optical Document Extraction
              </h2>
              <p>
                Optical character recognition (OCR) and document extraction tools are provided to assist in data entry. Extracted values are tagged with provenance markers and must be verified by a human user or licensed surveyor prior to financial reliance.
              </p>
            </section>
          </div>
        </section>
      </main>

      <PublicFooter />
    </div>
  );
}
